feat(android): add v8 heap tool
Tencent/Hippy pull request #1803
Opened 2022-05-01 04:29 UTC by linjinze999

Before submitting a new pull request, please make sure:

- [x] Test cases have been added/updated/passed for the code you will submit.
- [x] Documentation has added or updated.
- [x] Commit message is following the [Convention Commit](https://conventionalcommits.org/) guideline with maximum 72 characters.
- [x] Squash the repeat code commits, short patches are welcome.

2022-05-01 04:29 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/Hippy?pullRequest=1803) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/Hippy?pullRequest=1803) before we can accept your contribution.<br/><hr/>**jinzelin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/Hippy?pullRequest=1803) it.</sub>

2022-05-05 03:14 UTC, churchill-zhang commented on android/sdk/src/main/jni/include/bridge/entry.h
> +            std::string heap_snapshot_chunk_data =
推荐带上size，另外这里为什么要转u8呢，data是buffer还是string？

2022-05-05 03:14 UTC, churchill-zhang commented on android/sdk/src/main/jni/src/bridge/entry.cc
> +  v8::HeapCodeStatistics* heap_code_statistics = new v8::HeapCodeStatistics();
最好用智能指针，不要用显示的new，需要用指针的地方用get获取裸指针。因为后续如果出现异常，极其容易遗忘delete

2022-05-05 03:14 UTC, churchill-zhang commented on android/sdk/src/main/jni/src/bridge/entry.cc
> +      TDF_BASE_DLOG(WARNING) << "GetHeapCodeStatistics, j_runtime_id invalid";
出现异常了，理论应该需要返回错误，提前返回。后续已经没必要执行了

2022-05-05 03:14 UTC, churchill-zhang commented on android/sdk/src/main/jni/src/bridge/entry.cc
> +  jclass java_class_hcs = j_env->FindClass("com/tencent/mtt/hippy/bridge/heap/HeapCodeStatistics");
是否遗忘了DeleteLocalRef

2022-05-05 03:14 UTC, churchill-zhang commented on android/sdk/src/main/jni/src/bridge/entry.cc
> +    TDF_BASE_DLOG(INFO) << "GetHeapSpaceStatisticsList begin, j_runtime_id = " << j_runtime_id;
j_runtime_id 异常时及早返回，也就没必要各种反射查找jclass了

2022-05-05 03:14 UTC, churchill-zhang commented on android/sdk/src/main/jni/src/bridge/entry.cc
> +    TDF_BASE_DLOG(INFO) << "GetHeapSpaceStatisticsList begin, j_runtime_id = " << j_runtime_id;
另外jni相关对象最好j_xxx命名，方便大家理解

2022-05-05 03:14 UTC, churchill-zhang commented on android/sdk/src/main/jni/src/bridge/entry.cc
> +            heap_space_statistics = nullptr;
非返回值的jobject需要显式释放引用

2022-05-05 03:14 UTC, churchill-zhang commented on android/sdk/src/main/jni/src/bridge/entry.cc
> +        TDF_BASE_DLOG(WARNING) << "GetHeapStatistics, j_runtime_id invalid";
同上，及早并释放资源

2022-05-05 03:14 UTC, churchill-zhang commented on android/sdk/src/main/jni/include/bridge/entry.h
> +#define HSOSA_FILE_OK 0
c++推荐用枚举

2022-05-05 03:18 UTC, churchill-zhang commented on android/sdk/src/main/jni/src/bridge/entry.cc
> +      v8::Isolate* isolate = std::static_pointer_cast<hippy::napi::V8VM>(runtime->GetEngine()->GetVM())->isolate_;
另外v8相关操作需要在v8线程，否则会crash。这里看不出来java一定是在js线程调用，那就需要c++显示postTask到js线程执行

2022-05-10 14:51 UTC, medns requested changes
Request changes

2022-05-10 15:29 UTC, linjinze999 commented
先关闭，另外提一个Pr，减少commit

2022-05-10 15:29 UTC, closed without merging