feat(driver): add promise reject handle
Tencent/Hippy pull request #2564
Opened 2022-10-21 06:55 UTC by omega-xiao

# Pre-PR Checklist

- [x] I added/updated relevant documentation.
- [x] I followed the [Convention Commit](https://conventionalcommits.org/) guideline with maximum 72 characters to submit commit message.
- [x] I squashed the repeated code commits.
- [x] I signed the [CLA].
- [x] I added/updated test cases to check the change I am making.
- [x] All existing and new tests are passing.

2022-12-02 10:29 UTC, churchill-zhang commented on framework/android/connector/driver/js/src/main/cpp/src/js_driver_jni.cc
> +  auto process_handle_callback = [ctx] {
不能强持有吧

2022-12-02 10:30 UTC, churchill-zhang commented on driver/js/src/modules/timer_module.cc
> +    ctx->ProcessPromiseReject();
这个不能只在这里加吧，每一个js task后都要检查

2023-01-05 09:21 UTC, zoomchan-cxj approved these changes

2023-02-06 02:51 UTC, ilikethese approved these changes

2023-04-03 02:22 UTC, zoomchan-cxj commented on driver/js/lib/modules/PromiseRejectHandle.js
> +    console.error(eventName, err);
没有 err

2023-04-04 02:29 UTC, zoomchan-cxj requested changes
fix comment issue

2023-04-16 07:20 UTC, zoomchan-cxj requested changes
need changed

2023-07-05 01:40 UTC, closed without merging