Feat/connect
Tencent/Hippy pull request #2713
Opened 2022-11-30 03:38 UTC by churchill-zhang

# Pre-PR Checklist

- [x] I added/updated relevant documentation.
- [x] I followed the [Convention Commit](https://conventionalcommits.org/) guideline with maximum 72 characters to submit commit message.
- [x] I squashed the repeated code commits.
- [x] I signed the [CLA].
- [x] I added/updated test cases to check the change I am making.
- [x] All existing and new tests are passing.

2022-11-30 06:11 UTC, lavnFan commented on framework/android/src/main/java/com/tencent/mtt/hippy/HippyEngineManagerImpl.java
>          }
没恢复

2022-11-30 07:09 UTC, medns requested changes
need to be change

2022-12-01 04:19 UTC, siguangli approved these changes

2022-12-01 06:39 UTC, ozonelmy approved these changes

2022-12-01 06:43 UTC, ilikethese approved these changes
TL;DR;

2022-12-01 09:26 UTC, lavnFan approved these changes
lgtm

2022-12-01 09:43 UTC, medns approved these changes
LGTM

2022-12-01 09:46 UTC, merged