feat: update performance guide
Tencent/Hippy pull request #2804
Opened 2022-12-16 02:22 UTC by wwwcg

# Pre-PR Checklist

- [x] I added/updated relevant documentation.
- [x] I followed the [Convention Commit](https://conventionalcommits.org/) guideline with maximum 72 characters to submit commit message.
- [x] I squashed the repeated code commits.
- [x] I signed the [CLA].
- [x] I added/updated test cases to check the change I am making.
- [x] All existing and new tests are passing.

2023-02-02 03:10 UTC, ozonelmy approved these changes
LGTM

2023-02-02 08:11 UTC, ilikethese approved these changes

2023-02-02 08:16 UTC, siguangli commented on android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java
> +                callback = new NativeCallback(mHandler) {
这里不用单独写个callback，与上面的mCallFunctionCallback 合并就行了

2023-02-03 10:45 UTC, zoomchan-cxj commented on docs/guide/performance.md
> +| JS引擎 | 初始化JS引擎耗时 | InitJsFramework | -- |
这里的Key为什么双端不做成一致？

2023-02-03 10:47 UTC, zoomchan-cxj commented on docs/guide/performance.md
> +```json
这个为什么是一个数组形式

2023-02-03 10:48 UTC, zoomchan-cxj commented on docs/guide/performance.md
> +}, ...] }
这个result 为什么是一个数组形式

2023-02-09 08:43 UTC, iPel commented on docs/guide/performance.md
> +| JS引擎 | 初始化JS引擎耗时 | InitJsFramework | -- |
已修改

2023-02-09 08:43 UTC, iPel commented on android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeManagerImpl.java
> +                callback = new NativeCallback(mHandler) {
已修改

2023-02-09 08:43 UTC, iPel commented on docs/guide/performance.md
> +}, ...] }
已修改

2023-02-09 08:48 UTC, ilikethese commented on android/sdk/src/main/jni/src/bridge/entry.cc
> +                       long long &load_end_millis) {
long long 和 函数参数想表达的意思看起来不一致，是不是用专门的时间类型做变量类型

2023-02-09 08:51 UTC, siguangli approved these changes

2023-02-09 09:29 UTC, ilikethese submitted a review, later dismissed
LGTM

2023-02-10 10:21 UTC, zoomchan-cxj approved these changes

2023-02-10 10:23 UTC, ozonelmy submitted a review, later dismissed
LGTM

2023-02-10 10:34 UTC, siguangli submitted a review, later dismissed

2023-02-10 11:23 UTC, zoomchan-cxj submitted a review, later dismissed

2023-02-13 01:56 UTC, churchill-zhang commented on docs/en-us/guide/performance.md
> +| JS engine | Initialize JS engine (Android only) | hippyInitJsFramework |
performance 建议和 w3c 对齐或者靠近。vendor 对于每一个使用 sdk 的业务来说并不是必须品，因此不需要额外列出来，另外 android 的引擎启动时间单独列出来也很奇怪，我们可以提供最基本的[Performance.now()](https://developer.mozilla.org/zh-CN/docs/Web/API/Performance/now) 和 [Performance.getEntries()](https://developer.mozilla.org/zh-CN/docs/Web/API/Performance/getEntries)

2023-02-13 02:28 UTC, ilikethese approved these changes

2023-02-13 05:01 UTC, zoomchan-cxj approved these changes

2023-02-13 09:45 UTC, medns requested changes
@churchill-zhang

2023-02-13 09:51 UTC, churchill-zhang requested changes

2023-02-13 09:51 UTC, churchill-zhang commented on android/sdk/src/main/jni/src/bridge/entry.cc
> +    {
这里的括号可以去掉，及时释放的价值不是很大，中间没什么很大内存需要清理，反而会给看代码的人疑惑，这里为什么会特殊

2023-02-13 09:51 UTC, churchill-zhang commented on android/sdk/src/main/jni/src/bridge/java2js.cc
> +void CallJavaReportLoadedTime(jobject j_obj,
CallJavaReportLoadedTime实际也是nativeCallback的一种，这里容易疑惑。推荐使用nativeCallback重载的方式来做

2023-02-13 13:08 UTC, iPel commented on android/sdk/src/main/jni/src/bridge/entry.cc
> +    {
已修改

2023-02-13 13:08 UTC, iPel commented on android/sdk/src/main/jni/src/bridge/java2js.cc
> +void CallJavaReportLoadedTime(jobject j_obj,
已修改

2023-02-13 13:30 UTC, wwwcg commented on docs/en-us/guide/performance.md
> +| JS engine | Initialize JS engine (Android only) | hippyInitJsFramework |
Performance.now已有，Performance.getEntries()计划后续与Performance.mark一起提供

2023-02-14 01:38 UTC, churchill-zhang submitted a review, later dismissed

2023-02-14 07:53 UTC, zoomchan-cxj submitted a review, later dismissed

2023-02-15 02:39 UTC, ozonelmy submitted a review, later dismissed

2023-02-21 02:27 UTC, siguangli approved these changes

2023-02-21 02:38 UTC, zoomchan-cxj approved these changes
LGTM

2023-02-21 02:45 UTC, ilikethese approved these changes

2023-02-21 03:05 UTC, medns requested changes

2023-02-21 03:29 UTC, iPel commented on android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java
> +    public native void callFunction(String action, long runtimeIdm,
reverted

2023-02-21 03:33 UTC, medns submitted a review, later dismissed
LGTM

2023-02-21 03:33 UTC, zoomchan-cxj submitted a review, later dismissed

2023-02-21 06:46 UTC, churchill-zhang submitted a review, later dismissed

2023-02-21 06:49 UTC, ilikethese submitted a review, later dismissed

2023-02-21 07:31 UTC, ilikethese approved these changes

2023-02-21 07:32 UTC, ozonelmy approved these changes

2023-02-21 07:41 UTC, churchill-zhang approved these changes

2023-02-21 07:43 UTC, zoomchan-cxj approved these changes

2023-02-21 07:45 UTC, medns approved these changes
LGTM

2023-02-22 02:37 UTC, siguangli approved these changes

2023-02-22 02:46 UTC, merged