fix(ios): fix ConsoleModule.log not working
Tencent/Hippy pull request #2812
Opened 2022-12-16 08:27 UTC by wwwcg

# Pre-PR Checklist

- [x] I added/updated relevant documentation.
- [x] I followed the [Convention Commit](https://conventionalcommits.org/) guideline with maximum 72 characters to submit commit message.
- [x] I squashed the repeated code commits.
- [x] I signed the [CLA].
- [x] I added/updated test cases to check the change I am making.
- [x] All existing and new tests are passing.

2022-12-16 10:03 UTC, zoomchan-cxj requested changes

2022-12-16 10:03 UTC, zoomchan-cxj commented on examples/hippy-react-demo/src/app.jsx
>    render() {
不要在render里加这个逻辑，要么就在初始化的时候

2022-12-16 12:18 UTC, wwwcg commented on examples/hippy-react-demo/src/app.jsx
>    render() {
已调整

2022-12-16 13:46 UTC, ozonelmy approved these changes

2022-12-19 01:55 UTC, churchill-zhang commented on examples/hippy-react-demo/src/app.jsx
调试代码记得删了

2022-12-19 01:58 UTC, churchill-zhang commented on ios/sdk/utils/HippyLog.mm
> +                    _HippyLogNativeInternal(HippyLogLevelInfo, "TDFCore", 0, @"%@", message);
这里确定是TDFCore吗

2022-12-19 01:59 UTC, churchill-zhang submitted a review, later dismissed

2022-12-19 03:14 UTC, zoomchan-cxj submitted a review, later dismissed
LGTM

2022-12-21 02:25 UTC, ozonelmy approved these changes

2022-12-28 07:04 UTC, zoomchan-cxj approved these changes
LGTM

2022-12-29 03:09 UTC, churchill-zhang approved these changes

2022-12-29 03:09 UTC, merged