feat(andr): add prod remotedebug, local bundle instead of remote server
Tencent/Hippy pull request #2849
Opened 2023-01-09 05:31 UTC by FE-xiaoJiang

# Pre-PR Checklist

- [x] I added/updated relevant documentation.
- [x] I followed the [Convention Commit](https://conventionalcommits.org/) guideline with maximum 72 characters to submit commit message.
- [x] I squashed the repeated code commits.
- [x] I signed the [CLA].
- [x] I added/updated test cases to check the change I am making.
- [x] All existing and new tests are passing.

2023-01-13 07:27 UTC, lavnFan commented on android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngine.java
> +    public boolean mProdRemoteDebugMode = false;
命名上有点拗口，onlyDebugMode 会不会好一点，而且也不需要区分 production ，remote 这些概念，就是仅负责调试不负责 bundle 加载

2023-01-13 07:31 UTC, lavnFan commented on android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java
> +    private void initJSEngine(int groupId, boolean mIsDevModule) {
和上边 initJSEngine 重复代码，建议重载调用

2023-01-13 07:32 UTC, lavnFan commented on android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java
> +    public void createDebugSocketClient(String wsDebugUrl, DebugWebSocketClient.JSDebuggerCallback cb) {
private 减小作用域

2023-01-13 07:38 UTC, lavnFan commented on android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java
> +        LogUtils.i("HippyBridgeImpl", debugUrl+" --- "+mDebugServerHost);
格式化一下，格式不对，中间的 --- 可以用 ： 替代就好

2023-01-13 07:38 UTC, lavnFan commented on examples/android-demo/src/main/java/com/tencent/mtt/hippy/example/MyActivity.java
> +                        mHippyEngine.getEngineContext().getBridgeManager().connectDebugUrl("ws://debugger.kg.qq.com/wsTarget/8395e152-f279-416d-8dda-06c9999c3ff5");
这一步可以去掉，把 ws://debugger.kg.qq.com/wsTarget/8395e152-f279-416d-8dda-06c9999c3ff5 赋值给 remoteServerUrl 是不是就好了，内部在判断是 debug 模式下自动去 connect？这样上边的 setRemoteServerData 也不需要

2023-01-13 07:38 UTC, lavnFan commented on android/sdk/src/main/java/com/tencent/mtt/hippy/devsupport/DevServerHelper.java
> +        return d_url;
合并一行

2023-02-05 08:33 UTC, FE-xiaoJiang commented on android/sdk/src/main/java/com/tencent/mtt/hippy/bridge/HippyBridgeImpl.java
> +    private void initJSEngine(int groupId, boolean mIsDevModule) {
ok，确实

2023-02-05 08:44 UTC, FE-xiaoJiang commented on examples/android-demo/src/main/java/com/tencent/mtt/hippy/example/MyActivity.java
> +                        mHippyEngine.getEngineContext().getBridgeManager().connectDebugUrl("ws://debugger.kg.qq.com/wsTarget/8395e152-f279-416d-8dda-06c9999c3ff5");
生产环境业务落地情况会有些变化，比如远程调试开启会根据具体项目来，那么在引擎预初始化的情况下，无法在一开始就确定这个引擎最终会用到哪个业务去，所以还是要在具体业务加载前才能确定最终的debugUrl，没有办法在引擎初始化就设置这个参数，所以这种情况下还是主动去connect更加合适

2023-02-06 02:40 UTC, zoomchan-cxj commented on packages/hippy-react/src/renderer/render.ts
> +    // nativeNode.tagName = targetNode.nativeName;
hippy-vue 和 hippy-vue-next 也要同时改

2023-02-06 03:03 UTC, FE-xiaoJiang commented on packages/hippy-react/src/renderer/render.ts
> +    // nativeNode.tagName = targetNode.nativeName;
oook，我同步处理一下

2023-02-07 03:33 UTC, lavnFan commented on android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngine.java
> +    public boolean mPureDebugMode = false;
与 变量 mProdRemoteDebugMode 一致性问题

2023-02-07 03:34 UTC, lavnFan commented on packages/hippy-react/src/renderer/render.ts
> +    // nativeNode.tagName = targetNode.nativeName;
不应该有注释的废弃代码

2023-02-07 08:47 UTC, FE-xiaoJiang commented on android/sdk/src/main/java/com/tencent/mtt/hippy/HippyEngine.java
> +    public boolean mPureDebugMode = false;
OK，我改成一致了，免得歧义

2023-02-17 09:35 UTC, siguangli submitted a review, later dismissed

2023-02-20 02:54 UTC, zoomchan-cxj requested changes
fix unit test error

2023-02-20 11:39 UTC, zoomchan-cxj approved these changes

2023-02-21 03:11 UTC, zoomchan-cxj approved these changes

2023-02-21 06:15 UTC, siguangli approved these changes

2023-02-21 06:17 UTC, merged