feat(layout): replace taitank layout and remove layout directory
Tencent/Hippy pull request #2850
Opened 2023-01-09 08:57 UTC by ilikethese

# Pre-PR Checklist

- [x] I added/updated relevant documentation.
- [x] I followed the [Convention Commit](https://conventionalcommits.org/) guideline with maximum 72 characters to submit commit message.
- [x] I squashed the repeated code commits.
- [x] I signed the [CLA].
- [x] I added/updated test cases to check the change I am making.
- [x] All existing and new tests are passing.

2023-01-09 09:02 UTC, churchill-zhang commented on dom/include/dom/taitank_layout_node.h
>  #include "dom/layout_node.h"
看起来没有中间层，如果使用yoga，这里是不是显式依赖taitank有问题？

2023-02-14 09:50 UTC, ozonelmy approved these changes
LGTM

2023-02-14 10:36 UTC, zoomchan-cxj approved these changes

2023-02-15 02:09 UTC, lavnFan submitted a review, later dismissed

2023-02-15 10:03 UTC, medns requested changes

2023-02-15 10:03 UTC, medns commented on dom/CMakeLists.txt
> +include("${PROJECT_ROOT_DIR}/buildconfig/cmake/GlobalPackagesModule.cmake")
unnessary include

2023-02-15 10:03 UTC, medns commented on dom/CMakeLists.txt
> +  target_include_directories(${PROJECT_NAME} PUBLIC ${taitank_SOURCE_DIR}/src)
maybe expose from taitank project?

2023-02-15 10:03 UTC, medns commented on framework/examples/ios-demo/clean_and_generate.sh
> +#!/bin/bash
Looks like this file is not necessary?

2023-02-16 02:27 UTC, ilikethese commented on dom/CMakeLists.txt
> +include("${PROJECT_ROOT_DIR}/buildconfig/cmake/GlobalPackagesModule.cmake")
fix

2023-02-16 02:27 UTC, ilikethese commented on dom/CMakeLists.txt
> +  target_include_directories(${PROJECT_NAME} PUBLIC ${taitank_SOURCE_DIR}/src)
fix

2023-02-16 02:39 UTC, ozonelmy commented on framework/examples/ios-demo/clean_and_generate.sh
> +#!/bin/bash
fixed

2023-02-21 04:06 UTC, medns approved these changes
LGTM

2023-02-24 02:30 UTC, ozonelmy approved these changes

2023-02-24 02:34 UTC, churchill-zhang approved these changes

2023-02-24 02:44 UTC, zoomchan-cxj approved these changes

2023-02-24 02:45 UTC, lavnFan approved these changes

2023-02-24 04:05 UTC, merged