Add getBoundingClient api
Tencent/Hippy pull request #2914
Opened 2023-02-06 13:36 UTC by wwwcg

Before submitting a new pull request, please make sure:

- [ ] Test cases have been added/updated/passed for the code you will submit.
- [ ] Documentation has added or updated.
- [ ] Commit message is following the [Convention Commit](https://conventionalcommits.org/) guideline with maximum 72 characters.
- [ ] Squash the repeat code commits, short patches are welcome.

2023-02-06 13:38 UTC, zoomchan-cxj submitted a review, later dismissed
LGTM

2023-02-07 06:25 UTC, ozonelmy submitted a review, later dismissed
LGTM

2023-02-07 09:50 UTC, siguangli commented on renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java
> +            Object param = params.get(0);
统一使用ArrayUtils获取

2023-02-07 09:50 UTC, siguangli commented on renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java
> +                relToContainer = ((HashMap<?, ?>) param).get(KEY_REL_TO_CONTAINER) == Boolean.TRUE;
统一使用MapUtils来获取

2023-02-08 05:11 UTC, iPel commented on renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java
> +            Object param = params.get(0);
已修改

2023-02-08 05:11 UTC, iPel commented on renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java
> +                relToContainer = ((HashMap<?, ?>) param).get(KEY_REL_TO_CONTAINER) == Boolean.TRUE;
已修改

2023-02-08 06:30 UTC, ozonelmy approved these changes
LGTM

2023-02-09 07:53 UTC, zoomchan-cxj submitted a review, later dismissed

2023-02-09 09:07 UTC, siguangli requested changes

2023-02-09 09:07 UTC, siguangli commented on renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java
> +        int[] pair = new int[2];
pair的定义最好放在下面 view.getLocationInWindow(pair); 之前，不然走rootview == null分支return以后就白new一个对象

2023-02-09 09:09 UTC, ozonelmy submitted a review, later dismissed
LGTM

2023-02-09 09:41 UTC, iPel commented on renderer/native/android/src/main/java/com/tencent/mtt/hippy/uimanager/HippyViewController.java
> +        int[] pair = new int[2];
已修改

2023-02-09 09:57 UTC, zoomchan-cxj approved these changes

2023-02-09 10:08 UTC, ozonelmy approved these changes
LGTM

2023-02-10 02:47 UTC, siguangli approved these changes

2023-02-10 03:09 UTC, merged