feat(voltron): add 3.0 voltron measure func and fix modal size error
Tencent/Hippy pull request #2930
Opened 2023-02-10 05:12 UTC by henryjin0511

# Pre-PR Checklist

- [x] I added/updated relevant documentation.
- [x] I followed the [Convention Commit](https://conventionalcommits.org/) guideline with maximum 72 characters to submit commit message.
- [x] I squashed the repeated code commits.
- [x] I signed the [CLA].
- [x] I added/updated test cases to check the change I am making.
- [x] All existing and new tests are passing.

2023-02-10 06:16 UTC, lvfen approved these changes

2023-02-10 06:21 UTC, skindhu approved these changes

2023-02-10 06:26 UTC, zoomchan-cxj requested changes
看需不需要替换一下voltron demo的内置 js包，native renderer的已经替换了

2023-02-10 06:34 UTC, henryjin0511 commented
> 看需不需要替换一下voltron demo的内置 js包，native renderer的已经替换了

已经重新build替换了最新的voltron demo内置js包

2023-02-10 06:41 UTC, zoomchan-cxj submitted a review, later dismissed
LGTM

2023-02-10 11:15 UTC, lvfen submitted a review, later dismissed

2023-02-13 03:02 UTC, skindhu approved these changes

2023-02-13 04:30 UTC, lvfen approved these changes

2023-02-13 04:38 UTC, skindhu approved these changes

2023-02-13 04:54 UTC, merged