feat(core): add snapshot for hippy
Tencent/Hippy pull request #2970
Opened 2023-02-24 02:19 UTC by churchill-zhang

# Pre-PR Checklist

- [x] I added/updated relevant documentation.
- [x] I followed the [Convention Commit](https://conventionalcommits.org/) guideline with maximum 72 characters to submit commit message.
- [x] I squashed the repeated code commits.
- [x] I signed the [CLA].
- [x] I added/updated test cases to check the change I am making.
- [x] All existing and new tests are passing.

2023-02-24 02:21 UTC, ilikethese submitted a review, later dismissed

2023-02-24 02:39 UTC, ozonelmy submitted a review, later dismissed
LGTM

2023-02-24 02:39 UTC, siguangli approved these changes

2023-02-27 02:39 UTC, medns requested changes
changes needs to be made

2023-02-28 07:37 UTC, zoomchan-cxj requested changes
js 是否需要判断属性存在性

2023-03-02 09:58 UTC, siguangli approved these changes

2023-03-02 10:56 UTC, zoomchan-cxj approved these changes

2023-03-02 11:25 UTC, ilikethese approved these changes

2023-03-02 11:26 UTC, siguangli submitted a review, later dismissed

2023-03-02 11:44 UTC, siguangli approved these changes

2023-03-02 11:47 UTC, ilikethese approved these changes

2023-03-03 07:00 UTC, churchill-zhang commented
> changes needs to be made

已拆多个commit

2023-03-03 07:01 UTC, churchill-zhang commented
> js 是否需要判断属性存在性

corejs相关改动已还原

2023-03-03 07:21 UTC, medns requested changes

2023-03-03 07:21 UTC, medns commented on android/sdk/src/main/jni/src/bridge/entry.cc
> +// REGISTER_EXTERNAL_REFERENCES(HandleUncaughtJsError)
unnecessary comment?

2023-03-03 07:21 UTC, medns commented on android/sdk/src/main/jni/src/bridge/entry.cc
> +// REGISTER_EXTERNAL_REFERENCES(NativeCallback)
unnecessary comment?

2023-03-03 07:21 UTC, medns commented on android/sdk/src/main/jni/src/bridge/entry.cc
> +  engine = nullptr;
unnecessary set to `nullptr`

2023-03-03 07:21 UTC, medns commented on core/include/core/vm/v8/snapshot_data.h
> +constexpr char kSdkVersion[] = "2.15.8";
SDK version may be imported from outside?

2023-03-03 07:21 UTC, medns commented on core/include/core/vm/v8/snapshot_data.h
> +  bool ReadMetaData();                // use meta data in buffer_holder
`Metadata` is a proper noun, change `ReadMetaData` to `ReadMetadata`

2023-03-03 07:21 UTC, medns commented on core/include/core/vm/v8/snapshot_serializer.h
> +  uint32_t position_ = 0;
change `position_` to a  `size_t` type

2023-03-03 07:21 UTC, medns commented on core/src/base/file.cc
> +                         bool is_auto_fill) {
why need auto fill?

2023-03-03 07:21 UTC, medns commented on core/src/vm/v8/snapshot_data.cc
> +bool SnapshotData::ReadMetaData() {
output detial messages(like a `read %s failed, excepted %s, received %s`) when an exception occurs

2023-03-03 07:21 UTC, medns commented on core/src/vm/v8/snapshot_serializer.cc
> +  memcpy(&buffer_[0] + position_, p, length);
use `std::copy_n` instead

2023-03-03 12:00 UTC, churchill-zhang commented on core/src/base/file.cc
> +                         bool is_auto_fill) {
读c风格字符串需要，避免外部拷贝

2023-03-06 00:16 UTC, ilikethese submitted a review, later dismissed

2023-03-06 07:51 UTC, siguangli approved these changes

2023-03-06 07:52 UTC, ilikethese approved these changes

2023-03-06 07:59 UTC, medns approved these changes
LGTM

2023-03-06 08:03 UTC, merged