fix(android): return size after loading gif
Tencent/Hippy pull request #3001
Opened 2023-03-02 13:43 UTC by Xuanquan-Zhuang

# Pre-PR Checklist

- [x] I added/updated relevant documentation.
- [x] I followed the [Convention Commit](https://conventionalcommits.org/) guideline with maximum 72 characters to submit commit message.
- [x] I squashed the repeated code commits.
- [x] I signed the [CLA].
- [x] I added/updated test cases to check the change I am making.
- [x] All existing and new tests are passing.

2023-03-02 13:48 UTC, zoomchan-cxj requested changes
1. 这个返回参数是否双端统一
2. success都有哪些值，分别 表示什么意思，要在官网文档补充
3. vue2、3 demo需要补充

2023-03-02 14:43 UTC, iPel commented on android/sdk/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageView.java
> +        } else if (mSourceDrawable instanceof HippyDrawable) {
HippyDrawable放第一个判断吧，这个条件绝大部分情况都会成立。

2023-03-04 01:37 UTC, Xuanquan-Zhuang commented on android/sdk/src/main/java/com/tencent/mtt/hippy/views/image/HippyImageView.java
> +        } else if (mSourceDrawable instanceof HippyDrawable) {
done

2023-03-06 06:36 UTC, zoomchan-cxj commented on docs/hippy-vue/components.md
> +| load        | 加载成功完成时调用此回调函数，`2.16.0`后支持参数返回，参数为：`evt: { nativeParams: { width: number, height: number, url: string } }`
这几个还是最好在 vue 代码里加上，不要用 nativeParams

2023-03-06 10:57 UTC, zoomchan-cxj commented on packages/hippy-vue-next/src/built-in-component.ts
> +    processEventData(evtData: EventsUnionType, nativeEventParams: NeedToTyped) {
image没有 scroll相关的吧，手势类的 click、touch不需要加，只加你这个需求需要的就行

2023-03-07 03:41 UTC, zoomchan-cxj commented on examples/hippy-vue-demo/src/components/demos/demo-img.vue
> +    onLoad(evt) {
evt 获取 width、height、url 可以通过解构写法
const { width, height, url } = evt

2023-03-07 03:41 UTC, zoomchan-cxj commented on examples/hippy-react-demo/src/components/Image/index.jsx
> +        onLoad={(result) => {
react 没有像vue 那样将result显示在页面上？

2023-03-07 03:43 UTC, zoomchan-cxj commented on packages/hippy-vue/src/elements/built-in.js
> +        case 'onLoad':
1. 用解构写法
const { width, height, url } =  nativeEventParams;

2. case 语句冒号后补上 { } 括号

2023-03-07 06:29 UTC, Xuanquan-Zhuang commented on examples/hippy-vue-demo/src/components/demos/demo-img.vue
> +    onLoad(evt) {
已修改

2023-03-07 06:29 UTC, Xuanquan-Zhuang commented on packages/hippy-vue/src/elements/built-in.js
> +        case 'onLoad':
已修改

2023-03-07 08:36 UTC, zoomchan-cxj commented on examples/hippy-vue-demo/src/components/demos/demo-img.vue
> +    onLoad(evt) {
const { width, height, url } = evt;
      this.gifLoadResult = {
        width,
        height,
        url,
      };

这样就可以了

2023-03-07 13:26 UTC, zoomchan-cxj approved these changes

2023-03-08 06:27 UTC, siguangli approved these changes

2023-03-08 06:37 UTC, merged