fix(devtools): fix the mapping between DOM tree and UI inspector
Tencent/Hippy pull request #4122
Opened 2024-11-12 13:15 UTC by Cyunong

Before submitting a new pull request, please make sure:

- [ ] Test cases have been added/updated/passed for the code you will submit.
- [ ] Documentation has added or updated.
- [ ] Commit message is following the [Convention Commit](https://conventionalcommits.org/) guideline with maximum 72 characters.
- [ ] Squash the repeat code commits, short patches are welcome.

2024-11-12 13:15 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/Hippy?pullRequest=4122) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/Hippy?pullRequest=4122) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/Hippy?pullRequest=4122) it.</sub>

2024-11-12 13:27 UTC, wwwcg requested changes

2024-11-12 13:27 UTC, wwwcg commented on renderer/native/ios/renderer/component/view/HippyViewManager.mm
> +      callback(@[locationDict]);
May crash if hitView is nil or not a HippyView

2024-11-12 13:27 UTC, wwwcg commented on renderer/native/ios/renderer/component/view/HippyViewManager.mm
> +      double locationY = [params[@"yOnScreen"] doubleValue];
avoid using hardcode string

2024-11-12 13:27 UTC, wwwcg commented on devtools/devtools-integration/native/include/devtools/devtools_utils.h
> +    static hippy::dom::DomArgument makeLocationArgument(double x, double y);
indent issue

2024-11-13 02:59 UTC, wwwcg commented on renderer/native/ios/renderer/component/view/HippyViewManager.mm
> +        HippyTagKey: @(-1),
这个-1 代表什么？要避免使用Magic number

2024-11-13 03:00 UTC, wwwcg commented on renderer/native/ios/renderer/component/view/HippyViewManager.mm
> +      UIView* hitView = [rootView hitTest:{locationX, locationY} withEvent:nil];
如果找不到hitView表现是怎样的？

2024-11-13 03:13 UTC, Cyunong commented on renderer/native/ios/renderer/component/view/HippyViewManager.mm
> +        HippyTagKey: @(-1),
-1是无效的tag，表示没有找到

2024-11-13 03:20 UTC, Cyunong commented on renderer/native/ios/renderer/component/view/HippyViewManager.mm
> +      UIView* hitView = [rootView hitTest:{locationX, locationY} withEvent:nil];
找不到hitView返回的tag仍是-1，后续会直接使用rootView作为选中的View

2024-11-14 03:07 UTC, wwwcg submitted a review, later dismissed

2024-11-15 12:01 UTC, siguangli approved these changes

2024-11-15 13:33 UTC, zealotchen0 approved these changes

2024-11-15 13:33 UTC, merged